### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by jpcoenen**
The base repoistory added an MIT license. It would be nice if that could be propagated to this fork, so https://github.com/go-redis/cache no longer has an unlicensed dependency.

### CODE REVIEW

**Comment by MorpheusXAUT** [comment]
Any news on this?
Unfortunately the [license checker](https://github.com/uw-labs/lichen) we use flags this dependency since no compatible license was found, flagging the go-redis/cache library as well.

**Comment by gongomgra** [comment]
@vmihailenco do you have any update on this? Can you add a license or approve this pull request? Thanks!

**Comment by vmihailenco** [comment]
:shrug: This is the first time I receive a notification for this PR

**Comment by vmihailenco** [comment]
...I guess because this is a fork

**Pull request merged**
